export const NAMES_TITLE = {
	CLIENT_NAME: 'Ф.И.О:',
	CLIENT_PHONE: 'Телефон:',
	CLIENT_EMAIL: 'Email:',
	CLIENT_BIRTHDAY: 'День рождения:',
	CLIENT_TELEGRAM: 'Telegram:',
	CLIENT_WHATSAPP: 'WhatsApp:',
	DATE_SHOOTING: 'Дата съёмки:',
	SHOOTING_TIME: 'Время съёмки:',
	DURATION_SHOOTING: 'Продолжительность:',
	BOOKING_LOCATION: 'Бронирование локации:',
	PAYMENT_LOCATION: 'Оплата локации:',
	COST_SHOOTING: 'Стоимость съемки:',
	PREPAYMENT: 'Предоплата:',
	CALCULATION: 'Расчет:',
	DEADLINE: 'Срок отдачи материала:',
	PROJECT_COMPLETED: 'Материал отдан:',
	CLIENT: 'Клиент:',
};
