export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	SET_CLIENT_DATA: 'SET_CLIENT_DATA',
	SET_PROJECT_DATA: 'SET_PROJECT_DATA',
	CLOSE_MODAL: 'CLOSE_MODAL',
	OPEN_MODAL: 'OPEN_MODAL',
	RESET_CLIENT_DATA: 'RESET_CLIENT_DATA',
	RESET_PROJECT_DATA: 'RESET_PROJECT_DATA',
	RESET_FINANCE_DATA: 'RESET_FINANCE_DATA',
	SET_FINANCE_DATA: 'SET_FINANCE_DATA',
};
